apiVersion: batch/v1
kind: CronJob
metadata:
  name: quakewatch-cron
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: quakewatch-cron
              image: busybox
              args:
                - /bin/sh
                - -c
                - echo "Running CronJob at $(date)"
          restartPolicy: OnFailure