apiVersion: v1
kind: Service
metadata:
  name: {{ include "quakewatch.fullname" . }}
  labels:
    {{- include "quakewatch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app.kubernetes.io/name: {{ include "quakewatch.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
